apiVersion: v1
name: cloudwatch-chart
description: A Helm chart for the ACK service controller for  ()
version: 0.11.3
appVersion: 0.11.3
home: https://github.com/aws-controllers-k8s/cloudwatch-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/cloudwatch-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name:  Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/cloudwatch-maintainer
keywords:
  - aws
  - kubernetes
  - cloudwatch
